export const ADMIN_ROUTE = '/admin' //
export const LOGIN_ROUTE = '/login' //
export const REGISTRATION_ROUTE = '/registration' //
export const TRIPS_ROUTE = '/trips'
export const EXCURSIONS_ROUTE = '/excursions'
export const EVENTS_ROUTE = '/events'
export const CLASSES_ROUTE = '/classes'
export const ATTENDANCE_ROUTE = '/attendance'
export const MAIN_ROUTE = '/' //